//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathieuShop.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPromotion
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateSubmission { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> NewQualificationId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Status Status { get; set; }
    }
}
