//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathieuShop.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public Nullable<int> OrdersId { get; set; }
        public Nullable<System.DateTime> DateReview { get; set; }
        public Nullable<int> Score { get; set; }
        public string Description { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
